import Head from 'next/head'
import Image from 'next/image'
import GoTrue from 'gotrue-js';

// Instantiate the GoTrue auth client with an optional configuration


import styles from '../styles/Home.module.css'

export default function Home() {
  // const auth = new GoTrue({
  //   APIUrl: 'https://<your domain name>/.netlify/identity',
  //   audience: '',
  //   setCookie: false,
  // });
  // auth.signup(email, password)
  // .then(response => console.log("Success!Check your inbox! ", response))
  // .catch(error => console.log("It 's an error", error));
  return (
    <div className={styles.container}>
      <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        
        
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
