import Head from "next/head";
import Image from "next/image";
import GoTrue from "gotrue-js";
// Instantiate the GoTrue auth client with an optional configuration

import styles from "../styles/Home.module.css";

export default function Home() {
  const auth = new GoTrue({
    APIUrl: "https://serene-vacherin-d0626b.netlify.app/",
    audience: "",
    setCookie: false,
  });
  const email = "email@gmail.com";
  const password = "123123@.s";
  auth
    .signup(email, password)
    .then((response) => console.log("Success!Check your inbox! ", response))
    .catch((error) => console.log("It 's an error", error));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>hola</div>
        <h1>Sign Up</h1>
        <h2>Log in</h2>
        <form name="login">
          <div class="message"></div>
          <p>
            <label>
              Email
              <br />
              <input type="email" name="email" required />
            </label>
          </p>
          <p>
            <label>
              Password
              <br />
              <input type="password" name="password" required />
            </label>
          </p>
          <button type="submit">Log in</button>
        </form>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
